// Code generated by "stringer -type=TypeFlags,ObjectFlags,SignatureFlags,NodeCheckFlags -bitflag -output=bitflags_stringer_generated.go"; DO NOT EDIT.

package checker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeFlagsNone-0]
	_ = x[TypeFlagsAny-1]
	_ = x[TypeFlagsUnknown-2]
	_ = x[TypeFlagsUndefined-4]
	_ = x[TypeFlagsNull-8]
	_ = x[TypeFlagsVoid-16]
	_ = x[TypeFlagsString-32]
	_ = x[TypeFlagsNumber-64]
	_ = x[TypeFlagsBigInt-128]
	_ = x[TypeFlagsBoolean-256]
	_ = x[TypeFlagsESSymbol-512]
	_ = x[TypeFlagsStringLiteral-1024]
	_ = x[TypeFlagsNumberLiteral-2048]
	_ = x[TypeFlagsBigIntLiteral-4096]
	_ = x[TypeFlagsBooleanLiteral-8192]
	_ = x[TypeFlagsUniqueESSymbol-16384]
	_ = x[TypeFlagsEnumLiteral-32768]
	_ = x[TypeFlagsEnum-65536]
	_ = x[TypeFlagsNonPrimitive-131072]
	_ = x[TypeFlagsNever-262144]
	_ = x[TypeFlagsTypeParameter-524288]
	_ = x[TypeFlagsObject-1048576]
	_ = x[TypeFlagsIndex-2097152]
	_ = x[TypeFlagsTemplateLiteral-4194304]
	_ = x[TypeFlagsStringMapping-8388608]
	_ = x[TypeFlagsSubstitution-16777216]
	_ = x[TypeFlagsIndexedAccess-33554432]
	_ = x[TypeFlagsConditional-67108864]
	_ = x[TypeFlagsUnion-134217728]
	_ = x[TypeFlagsIntersection-268435456]
	_ = x[TypeFlagsReserved1-536870912]
	_ = x[TypeFlagsReserved2-1073741824]
	_ = x[TypeFlagsReserved3-2147483648]
}

const _TypeFlags_name = "TypeFlagsAnyTypeFlagsUnknownTypeFlagsUndefinedTypeFlagsNullTypeFlagsVoidTypeFlagsStringTypeFlagsNumberTypeFlagsBigIntTypeFlagsBooleanTypeFlagsESSymbolTypeFlagsStringLiteralTypeFlagsNumberLiteralTypeFlagsBigIntLiteralTypeFlagsBooleanLiteralTypeFlagsUniqueESSymbolTypeFlagsEnumLiteralTypeFlagsEnumTypeFlagsNonPrimitiveTypeFlagsNeverTypeFlagsTypeParameterTypeFlagsObjectTypeFlagsIndexTypeFlagsTemplateLiteralTypeFlagsStringMappingTypeFlagsSubstitutionTypeFlagsIndexedAccessTypeFlagsConditionalTypeFlagsUnionTypeFlagsIntersectionTypeFlagsReserved1TypeFlagsReserved2TypeFlagsReserved3"

var (
	_TypeFlags_index  = [...]uint16{0, 12, 28, 46, 59, 72, 87, 102, 117, 133, 150, 172, 194, 216, 239, 262, 282, 295, 316, 330, 352, 367, 381, 405, 427, 448, 470, 490, 504, 525, 543, 561, 579}
	_TypeFlags_values = [...]TypeFlags{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608, 16777216, 33554432, 67108864, 134217728, 268435456, 536870912, 1073741824, 2147483648}
)

func (i TypeFlags) String() string {
	if i == 0 {
		return "TypeFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _TypeFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _TypeFlags_name[_TypeFlags_index[idx]:_TypeFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("TypeFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ObjectFlagsNone-0]
	_ = x[ObjectFlagsClass-1]
	_ = x[ObjectFlagsInterface-2]
	_ = x[ObjectFlagsReference-4]
	_ = x[ObjectFlagsTuple-8]
	_ = x[ObjectFlagsAnonymous-16]
	_ = x[ObjectFlagsMapped-32]
	_ = x[ObjectFlagsInstantiated-64]
	_ = x[ObjectFlagsObjectLiteral-128]
	_ = x[ObjectFlagsEvolvingArray-256]
	_ = x[ObjectFlagsObjectLiteralPatternWithComputedProperties-512]
	_ = x[ObjectFlagsReverseMapped-1024]
	_ = x[ObjectFlagsJsxAttributes-2048]
	_ = x[ObjectFlagsJSLiteral-4096]
	_ = x[ObjectFlagsFreshLiteral-8192]
	_ = x[ObjectFlagsArrayLiteral-16384]
	_ = x[ObjectFlagsPrimitiveUnion-32768]
	_ = x[ObjectFlagsContainsWideningType-65536]
	_ = x[ObjectFlagsContainsObjectOrArrayLiteral-131072]
	_ = x[ObjectFlagsNonInferrableType-262144]
	_ = x[ObjectFlagsCouldContainTypeVariablesComputed-524288]
	_ = x[ObjectFlagsCouldContainTypeVariables-1048576]
	_ = x[ObjectFlagsMembersResolved-2097152]
}

const _ObjectFlags_name = "ObjectFlagsClassObjectFlagsInterfaceObjectFlagsReferenceObjectFlagsTupleObjectFlagsAnonymousObjectFlagsMappedObjectFlagsInstantiatedObjectFlagsObjectLiteralObjectFlagsEvolvingArrayObjectFlagsObjectLiteralPatternWithComputedPropertiesObjectFlagsReverseMappedObjectFlagsJsxAttributesObjectFlagsJSLiteralObjectFlagsFreshLiteralObjectFlagsArrayLiteralObjectFlagsPrimitiveUnionObjectFlagsContainsWideningTypeObjectFlagsContainsObjectOrArrayLiteralObjectFlagsNonInferrableTypeObjectFlagsCouldContainTypeVariablesComputedObjectFlagsCouldContainTypeVariablesObjectFlagsMembersResolved"

var (
	_ObjectFlags_index  = [...]uint16{0, 16, 36, 56, 72, 92, 109, 132, 156, 180, 233, 257, 281, 301, 324, 347, 372, 403, 442, 470, 514, 550, 576}
	_ObjectFlags_values = [...]ObjectFlags{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152}
)

func (i ObjectFlags) String() string {
	if i == 0 {
		return "ObjectFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _ObjectFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _ObjectFlags_name[_ObjectFlags_index[idx]:_ObjectFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("ObjectFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SignatureFlagsNone-0]
	_ = x[SignatureFlagsHasRestParameter-1]
	_ = x[SignatureFlagsHasLiteralTypes-2]
	_ = x[SignatureFlagsConstruct-4]
	_ = x[SignatureFlagsAbstract-8]
	_ = x[SignatureFlagsIsInnerCallChain-16]
	_ = x[SignatureFlagsIsOuterCallChain-32]
	_ = x[SignatureFlagsIsUntypedSignatureInJSFile-64]
	_ = x[SignatureFlagsIsNonInferrable-128]
	_ = x[SignatureFlagsIsSignatureCandidateForOverloadFailure-256]
}

const _SignatureFlags_name = "SignatureFlagsHasRestParameterSignatureFlagsHasLiteralTypesSignatureFlagsConstructSignatureFlagsAbstractSignatureFlagsIsInnerCallChainSignatureFlagsIsOuterCallChainSignatureFlagsIsUntypedSignatureInJSFileSignatureFlagsIsNonInferrableSignatureFlagsIsSignatureCandidateForOverloadFailure"

var (
	_SignatureFlags_index  = [...]uint16{0, 30, 59, 82, 104, 134, 164, 204, 233, 285}
	_SignatureFlags_values = [...]SignatureFlags{1, 2, 4, 8, 16, 32, 64, 128, 256}
)

func (i SignatureFlags) String() string {
	if i == 0 {
		return "SignatureFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _SignatureFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _SignatureFlags_name[_SignatureFlags_index[idx]:_SignatureFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("SignatureFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeCheckFlagsNone-0]
	_ = x[NodeCheckFlagsTypeChecked-1]
	_ = x[NodeCheckFlagsContextChecked-64]
	_ = x[NodeCheckFlagsEnumValuesComputed-1024]
	_ = x[NodeCheckFlagsAssignmentsMarked-131072]
	_ = x[NodeCheckFlagsInCheckIdentifier-4194304]
	_ = x[NodeCheckFlagsInitializerIsUndefined-16777216]
	_ = x[NodeCheckFlagsInitializerIsUndefinedComputed-33554432]
}

const _NodeCheckFlags_name = "NodeCheckFlagsTypeCheckedNodeCheckFlagsContextCheckedNodeCheckFlagsEnumValuesComputedNodeCheckFlagsAssignmentsMarkedNodeCheckFlagsInCheckIdentifierNodeCheckFlagsInitializerIsUndefinedNodeCheckFlagsInitializerIsUndefinedComputed"

var (
	_NodeCheckFlags_index  = [...]uint16{0, 25, 53, 85, 116, 147, 183, 227}
	_NodeCheckFlags_values = [...]NodeCheckFlags{1, 64, 1024, 131072, 4194304, 16777216, 33554432}
)

func (i NodeCheckFlags) String() string {
	if i == 0 {
		return "NodeCheckFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _NodeCheckFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _NodeCheckFlags_name[_NodeCheckFlags_index[idx]:_NodeCheckFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("NodeCheckFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}
