// Code generated by "stringer -type=NodeFlags,ModifierFlags,SymbolFlags,CheckFlags,TokenFlags -bitflag -output=bitflags_stringer_generated.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeFlagsNone-0]
	_ = x[NodeFlagsLet-1]
	_ = x[NodeFlagsConst-2]
	_ = x[NodeFlagsUsing-4]
	_ = x[NodeFlagsReparsed-8]
	_ = x[NodeFlagsSynthesized-16]
	_ = x[NodeFlagsOptionalChain-32]
	_ = x[NodeFlagsExportContext-64]
	_ = x[NodeFlagsContainsThis-128]
	_ = x[NodeFlagsHasImplicitReturn-256]
	_ = x[NodeFlagsHasExplicitReturn-512]
	_ = x[NodeFlagsDisallowInContext-1024]
	_ = x[NodeFlagsYieldContext-2048]
	_ = x[NodeFlagsDecoratorContext-4096]
	_ = x[NodeFlagsAwaitContext-8192]
	_ = x[NodeFlagsTypeExcludesFlags-10240]
	_ = x[NodeFlagsDisallowConditionalTypesContext-16384]
	_ = x[NodeFlagsThisNodeHasError-32768]
	_ = x[NodeFlagsJavaScriptFile-65536]
	_ = x[NodeFlagsThisNodeOrAnySubNodesHasError-131072]
	_ = x[NodeFlagsPossiblyContainsDynamicImport-524288]
	_ = x[NodeFlagsPossiblyContainsImportMeta-1048576]
	_ = x[NodeFlagsPermanentlySetIncrementalFlags-1572864]
	_ = x[NodeFlagsHasJSDoc-2097152]
	_ = x[NodeFlagsJSDoc-4194304]
	_ = x[NodeFlagsAmbient-8388608]
	_ = x[NodeFlagsInWithStatement-16777216]
	_ = x[NodeFlagsContextFlags-25263104]
	_ = x[NodeFlagsJsonFile-33554432]
	_ = x[NodeFlagsPossiblyContainsDeprecatedTag-67108864]
	_ = x[NodeFlagsUnreachable-134217728]
}

const _NodeFlags_name = "NodeFlagsLetNodeFlagsConstNodeFlagsUsingNodeFlagsReparsedNodeFlagsSynthesizedNodeFlagsOptionalChainNodeFlagsExportContextNodeFlagsContainsThisNodeFlagsHasImplicitReturnNodeFlagsHasExplicitReturnNodeFlagsDisallowInContextNodeFlagsYieldContextNodeFlagsDecoratorContextNodeFlagsAwaitContextNodeFlagsTypeExcludesFlagsNodeFlagsDisallowConditionalTypesContextNodeFlagsThisNodeHasErrorNodeFlagsJavaScriptFileNodeFlagsThisNodeOrAnySubNodesHasErrorNodeFlagsPossiblyContainsDynamicImportNodeFlagsPossiblyContainsImportMetaNodeFlagsPermanentlySetIncrementalFlagsNodeFlagsHasJSDocNodeFlagsJSDocNodeFlagsAmbientNodeFlagsInWithStatementNodeFlagsContextFlagsNodeFlagsJsonFileNodeFlagsPossiblyContainsDeprecatedTagNodeFlagsUnreachable"

var (
	_NodeFlags_index  = [...]uint16{0, 12, 26, 40, 57, 77, 99, 121, 142, 168, 194, 220, 241, 266, 287, 313, 353, 378, 401, 439, 477, 512, 551, 568, 582, 598, 622, 643, 660, 698, 718}
	_NodeFlags_values = [...]NodeFlags{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 10240, 16384, 32768, 65536, 131072, 524288, 1048576, 1572864, 2097152, 4194304, 8388608, 16777216, 25263104, 33554432, 67108864, 134217728}
)

func (i NodeFlags) String() string {
	if i == 0 {
		return "NodeFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _NodeFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _NodeFlags_name[_NodeFlags_index[idx]:_NodeFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("NodeFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModifierFlagsNone-0]
	_ = x[ModifierFlagsPublic-1]
	_ = x[ModifierFlagsPrivate-2]
	_ = x[ModifierFlagsProtected-4]
	_ = x[ModifierFlagsReadonly-8]
	_ = x[ModifierFlagsOverride-16]
	_ = x[ModifierFlagsExport-32]
	_ = x[ModifierFlagsAbstract-64]
	_ = x[ModifierFlagsAmbient-128]
	_ = x[ModifierFlagsStatic-256]
	_ = x[ModifierFlagsAccessor-512]
	_ = x[ModifierFlagsAsync-1024]
	_ = x[ModifierFlagsDefault-2048]
	_ = x[ModifierFlagsConst-4096]
	_ = x[ModifierFlagsIn-8192]
	_ = x[ModifierFlagsOut-16384]
	_ = x[ModifierFlagsDecorator-32768]
	_ = x[ModifierFlagsDeprecated-65536]
	_ = x[ModifierFlagsJSDocPublic-8388608]
	_ = x[ModifierFlagsJSDocPrivate-16777216]
	_ = x[ModifierFlagsJSDocProtected-33554432]
	_ = x[ModifierFlagsJSDocReadonly-67108864]
	_ = x[ModifierFlagsJSDocOverride-134217728]
	_ = x[ModifierFlagsHasComputedJSDocModifiers-268435456]
	_ = x[ModifierFlagsHasComputedFlags-536870912]
}

const _ModifierFlags_name = "ModifierFlagsPublicModifierFlagsPrivateModifierFlagsProtectedModifierFlagsReadonlyModifierFlagsOverrideModifierFlagsExportModifierFlagsAbstractModifierFlagsAmbientModifierFlagsStaticModifierFlagsAccessorModifierFlagsAsyncModifierFlagsDefaultModifierFlagsConstModifierFlagsInModifierFlagsOutModifierFlagsDecoratorModifierFlagsDeprecatedModifierFlagsJSDocPublicModifierFlagsJSDocPrivateModifierFlagsJSDocProtectedModifierFlagsJSDocReadonlyModifierFlagsJSDocOverrideModifierFlagsHasComputedJSDocModifiersModifierFlagsHasComputedFlags"

var (
	_ModifierFlags_index  = [...]uint16{0, 19, 39, 61, 82, 103, 122, 143, 163, 182, 203, 221, 241, 259, 274, 290, 312, 335, 359, 384, 411, 437, 463, 501, 530}
	_ModifierFlags_values = [...]ModifierFlags{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 8388608, 16777216, 33554432, 67108864, 134217728, 268435456, 536870912}
)

func (i ModifierFlags) String() string {
	if i == 0 {
		return "ModifierFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _ModifierFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _ModifierFlags_name[_ModifierFlags_index[idx]:_ModifierFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("ModifierFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SymbolFlagsNone-0]
	_ = x[SymbolFlagsFunctionScopedVariable-1]
	_ = x[SymbolFlagsBlockScopedVariable-2]
	_ = x[SymbolFlagsProperty-4]
	_ = x[SymbolFlagsEnumMember-8]
	_ = x[SymbolFlagsFunction-16]
	_ = x[SymbolFlagsClass-32]
	_ = x[SymbolFlagsInterface-64]
	_ = x[SymbolFlagsConstEnum-128]
	_ = x[SymbolFlagsRegularEnum-256]
	_ = x[SymbolFlagsValueModule-512]
	_ = x[SymbolFlagsNamespaceModule-1024]
	_ = x[SymbolFlagsTypeLiteral-2048]
	_ = x[SymbolFlagsObjectLiteral-4096]
	_ = x[SymbolFlagsMethod-8192]
	_ = x[SymbolFlagsConstructor-16384]
	_ = x[SymbolFlagsGetAccessor-32768]
	_ = x[SymbolFlagsSetAccessor-65536]
	_ = x[SymbolFlagsSignature-131072]
	_ = x[SymbolFlagsTypeParameter-262144]
	_ = x[SymbolFlagsTypeAlias-524288]
	_ = x[SymbolFlagsExportValue-1048576]
	_ = x[SymbolFlagsAlias-2097152]
	_ = x[SymbolFlagsPrototype-4194304]
	_ = x[SymbolFlagsExportStar-8388608]
	_ = x[SymbolFlagsOptional-16777216]
	_ = x[SymbolFlagsTransient-33554432]
	_ = x[SymbolFlagsAssignment-67108864]
	_ = x[SymbolFlagsModuleExports-134217728]
	_ = x[SymbolFlagsConstEnumOnlyModule-268435456]
	_ = x[SymbolFlagsReplaceableByMethod-536870912]
	_ = x[SymbolFlagsAll-1073741823]
	_ = x[SymbolFlagsGlobalLookup-1073741824]
}

const _SymbolFlags_name = "SymbolFlagsFunctionScopedVariableSymbolFlagsBlockScopedVariableSymbolFlagsPropertySymbolFlagsEnumMemberSymbolFlagsFunctionSymbolFlagsClassSymbolFlagsInterfaceSymbolFlagsConstEnumSymbolFlagsRegularEnumSymbolFlagsValueModuleSymbolFlagsNamespaceModuleSymbolFlagsTypeLiteralSymbolFlagsObjectLiteralSymbolFlagsMethodSymbolFlagsConstructorSymbolFlagsGetAccessorSymbolFlagsSetAccessorSymbolFlagsSignatureSymbolFlagsTypeParameterSymbolFlagsTypeAliasSymbolFlagsExportValueSymbolFlagsAliasSymbolFlagsPrototypeSymbolFlagsExportStarSymbolFlagsOptionalSymbolFlagsTransientSymbolFlagsAssignmentSymbolFlagsModuleExportsSymbolFlagsConstEnumOnlyModuleSymbolFlagsReplaceableByMethodSymbolFlagsAllSymbolFlagsGlobalLookup"

var (
	_SymbolFlags_index  = [...]uint16{0, 33, 63, 82, 103, 122, 138, 158, 178, 200, 222, 248, 270, 294, 311, 333, 355, 377, 397, 421, 441, 463, 479, 499, 520, 539, 559, 580, 604, 634, 664, 678, 701}
	_SymbolFlags_values = [...]SymbolFlags{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608, 16777216, 33554432, 67108864, 134217728, 268435456, 536870912, 1073741823, 1073741824}
)

func (i SymbolFlags) String() string {
	if i == 0 {
		return "SymbolFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _SymbolFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _SymbolFlags_name[_SymbolFlags_index[idx]:_SymbolFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("SymbolFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CheckFlagsNone-0]
	_ = x[CheckFlagsInstantiated-1]
	_ = x[CheckFlagsSyntheticProperty-2]
	_ = x[CheckFlagsSyntheticMethod-4]
	_ = x[CheckFlagsReadonly-8]
	_ = x[CheckFlagsReadPartial-16]
	_ = x[CheckFlagsWritePartial-32]
	_ = x[CheckFlagsHasNonUniformType-64]
	_ = x[CheckFlagsHasLiteralType-128]
	_ = x[CheckFlagsContainsPublic-256]
	_ = x[CheckFlagsContainsProtected-512]
	_ = x[CheckFlagsContainsPrivate-1024]
	_ = x[CheckFlagsContainsStatic-2048]
	_ = x[CheckFlagsLate-4096]
	_ = x[CheckFlagsReverseMapped-8192]
	_ = x[CheckFlagsOptionalParameter-16384]
	_ = x[CheckFlagsRestParameter-32768]
	_ = x[CheckFlagsDeferredType-65536]
	_ = x[CheckFlagsHasNeverType-131072]
	_ = x[CheckFlagsMapped-262144]
	_ = x[CheckFlagsStripOptional-524288]
	_ = x[CheckFlagsUnresolved-1048576]
	_ = x[CheckFlagsIsDiscriminantComputed-2097152]
	_ = x[CheckFlagsIsDiscriminant-4194304]
	_ = x[CheckFlagsIndexSymbol-8388608]
}

const _CheckFlags_name = "CheckFlagsInstantiatedCheckFlagsSyntheticPropertyCheckFlagsSyntheticMethodCheckFlagsReadonlyCheckFlagsReadPartialCheckFlagsWritePartialCheckFlagsHasNonUniformTypeCheckFlagsHasLiteralTypeCheckFlagsContainsPublicCheckFlagsContainsProtectedCheckFlagsContainsPrivateCheckFlagsContainsStaticCheckFlagsLateCheckFlagsReverseMappedCheckFlagsOptionalParameterCheckFlagsRestParameterCheckFlagsDeferredTypeCheckFlagsHasNeverTypeCheckFlagsMappedCheckFlagsStripOptionalCheckFlagsUnresolvedCheckFlagsIsDiscriminantComputedCheckFlagsIsDiscriminantCheckFlagsIndexSymbol"

var (
	_CheckFlags_index  = [...]uint16{0, 22, 49, 74, 92, 113, 135, 162, 186, 210, 237, 262, 286, 300, 323, 350, 373, 395, 417, 433, 456, 476, 508, 532, 553}
	_CheckFlags_values = [...]CheckFlags{1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608}
)

func (i CheckFlags) String() string {
	if i == 0 {
		return "CheckFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _CheckFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _CheckFlags_name[_CheckFlags_index[idx]:_CheckFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("CheckFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenFlagsNone-0]
	_ = x[TokenFlagsPrecedingLineBreak-1]
	_ = x[TokenFlagsPrecedingJSDocComment-2]
	_ = x[TokenFlagsUnterminated-4]
	_ = x[TokenFlagsExtendedUnicodeEscape-8]
	_ = x[TokenFlagsScientific-16]
	_ = x[TokenFlagsOctal-32]
	_ = x[TokenFlagsHexSpecifier-64]
	_ = x[TokenFlagsBinarySpecifier-128]
	_ = x[TokenFlagsOctalSpecifier-256]
	_ = x[TokenFlagsBinaryOrOctalSpecifier-384]
	_ = x[TokenFlagsWithSpecifier-448]
	_ = x[TokenFlagsContainsSeparator-512]
	_ = x[TokenFlagsUnicodeEscape-1024]
	_ = x[TokenFlagsContainsInvalidEscape-2048]
	_ = x[TokenFlagsHexEscape-4096]
	_ = x[TokenFlagsTemplateLiteralLikeFlags-7180]
	_ = x[TokenFlagsContainsLeadingZero-8192]
	_ = x[TokenFlagsContainsInvalidSeparator-16384]
	_ = x[TokenFlagsNumericLiteralFlags-25584]
	_ = x[TokenFlagsIsInvalid-26656]
	_ = x[TokenFlagsPrecedingJSDocLeadingAsterisks-32768]
	_ = x[TokenFlagsSingleQuote-65536]
	_ = x[TokenFlagsStringLiteralFlags-72716]
	_ = x[TokenFlagsPrecedingJSDocWithDeprecated-131072]
	_ = x[TokenFlagsPrecedingJSDocWithSeeOrLink-262144]
}

const _TokenFlags_name = "TokenFlagsPrecedingLineBreakTokenFlagsPrecedingJSDocCommentTokenFlagsUnterminatedTokenFlagsExtendedUnicodeEscapeTokenFlagsScientificTokenFlagsOctalTokenFlagsHexSpecifierTokenFlagsBinarySpecifierTokenFlagsOctalSpecifierTokenFlagsBinaryOrOctalSpecifierTokenFlagsWithSpecifierTokenFlagsContainsSeparatorTokenFlagsUnicodeEscapeTokenFlagsContainsInvalidEscapeTokenFlagsHexEscapeTokenFlagsTemplateLiteralLikeFlagsTokenFlagsContainsLeadingZeroTokenFlagsContainsInvalidSeparatorTokenFlagsNumericLiteralFlagsTokenFlagsIsInvalidTokenFlagsPrecedingJSDocLeadingAsterisksTokenFlagsSingleQuoteTokenFlagsStringLiteralFlagsTokenFlagsPrecedingJSDocWithDeprecatedTokenFlagsPrecedingJSDocWithSeeOrLink"

var (
	_TokenFlags_index  = [...]uint16{0, 28, 59, 81, 112, 132, 147, 169, 194, 218, 250, 273, 300, 323, 354, 373, 407, 436, 470, 499, 518, 558, 579, 607, 645, 682}
	_TokenFlags_values = [...]TokenFlags{1, 2, 4, 8, 16, 32, 64, 128, 256, 384, 448, 512, 1024, 2048, 4096, 7180, 8192, 16384, 25584, 26656, 32768, 65536, 72716, 131072, 262144}
)

func (i TokenFlags) String() string {
	if i == 0 {
		return "TokenFlagsNone"
	}
	var b []byte
	rem := i
	for idx, v := range _TokenFlags_values {
		if rem&v == v {
			if len(b) > 0 {
				b = append(b, '|')
			}
			b = append(b, _TokenFlags_name[_TokenFlags_index[idx]:_TokenFlags_index[idx+1]]...)
			rem &^= v
		}
	}
	if rem != 0 {
		if len(b) > 0 {
			b = append(b, '|')
		}
		b = append(b, ("TokenFlags(" + strconv.FormatInt(int64(rem), 10) + ")")...)
	}
	return string(b)
}
